### PR TITLE
Development Step 1 Parts f-j ClinVar File Upload to DNAnexus

### PR DESCRIPTION
**Pull request by PolarisAstrum-NHS**
Step 1 parts f-j of the Phoenix development plan.

Successful DNAnexus job: https://platform.dnanexus.com/panx/projects/GkxxZq843Zq2f0Gk3Z40p7BJ/monitor/job/GpYk96Q43Zq29PPVpKpFZBx8

Added:
- Read DNAnexus development project id from Phoenix config file (provided as app input)
- Using name of most recent clinvar annotation resource file for b38, generate folder name for update in development DNAnexus project
- Download clinvar annotation resource files to running DNAnexus worker node using FTP link and ftplib
- Renaming of clinvar files to add "_b38_withchr"
- Uploading clinvar files from DNAnexus worker node to update folder of development project
- Return DNAnexus file IDs for vcf and index file uploaded

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/3)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/3)* status: all files reviewed, 3 unresolved discussions (waiting on @pofuoku and @PolarisAstrum-NHS)

___
*[`bin/utils/util.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O2yyXw6D1PuiljlT0mq:-O2yyXw6D1PuiljlT0mr:blqgbse) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/utils/util.py#L45)):*
> ```Python
>     """
>     # read checksum file from path
>     try:
> ```

if you are just checking that the file exists, you can do an assert using the pathlib library
___
*[`bin/utils/util.py` line 48 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O2yyx6mCW8SVdE0ulQh:-O2yyx6mCW8SVdE0ulQi:bps1pp5) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/utils/util.py#L48)):*
> ```Python
>         with open(checksum_path, "r") as file:
>             for line in file:
>                 md5_checksum = line[0:32]
> ```

additionally, you can do `f.read()` to get the content of the md5 file
___
*[`bin/utils/util.py` line 109 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O2z-pUY2xIYKa32LlKt:-O2z-pUY2xIYKa32LlKu:bk0qrt3) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/utils/util.py#L109)):*
> ```Python
> 
> 
> def download_file_upload_DNAnexus(
> ```

i'm not a fan of functions that do multiple things, you should try and separate functionality in order to ease unitesting for example

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/3)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @pofuoku and @Yu-jinKim)

___
*[`bin/utils/util.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O2yyXw6D1PuiljlT0mq:-O31woao5JSCNpcIlkx0:b-kciry4) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/utils/util.py#L45)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

if you are just checking that the file exists, you can do an assert using the pathlib library
</blockquote></details>

This is here for exception handling. I need to read the contents of the file, not only check that it exists
___
*[`bin/utils/util.py` line 48 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O2yyx6mCW8SVdE0ulQh:-O31x1wd1EQCEgeIqwzo:bb6un1j) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/utils/util.py#L48)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

additionally, you can do `f.read()` to get the content of the md5 file
</blockquote></details>

Done
___
*[`bin/utils/util.py` line 109 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O2z-pUY2xIYKa32LlKt:-O326j2p10q0hNEDcHtY:bpem5or) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/utils/util.py#L109)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i'm not a fan of functions that do multiple things, you should try and separate functionality in order to ease unitesting for example
</blockquote></details>

The second half of the function has been added to upload_file_DNAnexus. The functions check_proj_folder_exists and check_project_exists have been added to make upload_file_DNAnexus generic to any project/folder.

**Review by Yu-jinKim — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/3)* status: all files reviewed, 1 unresolved discussion (waiting on @pofuoku)

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pofuoku)

**Review by pofuoku — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/3)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @PolarisAstrum-NHS and @Yu-jinKim)

___
*[`bin/clinvar_file_fetcher.py` line 126 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32aZtB-zJjqwlGTkv2:-O32aZtB-zJjqwlGTkv3:b-viyz1k) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/clinvar_file_fetcher.py#L126)):*
> ```Python
>             "Matching checksum could not be found for most recent ClinVar VCF"
>             + " on ncbi website"
>         )
> ```

Here, the comment and the code says you're checking for index file but the following RuntimeError says checksum couldn't be found. Do you want to check if `clinvar_checksum_file` in `file_list` or the comment on the error message an oversight?



_Code quote:_
```Python
    # check index file exists on website
    if recent_tbi_file not in file_list:
        raise RuntimeError(
            "Matching checksum could not be found for most recent ClinVar VCF"
            + " on ncbi website"
        )
```
___
*[`bin/clinvar_file_fetcher.py` line 156 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32gZZSBNOAY0iAPCqw:-O32gZZSBNOAY0iAPCqx:b3o0aml) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/clinvar_file_fetcher.py#L156)):*
> ```Python
>     full_website_link = f"{clinvar_base_link}{clinvar_link_path}"
>     vcf_basename = recent_vcf_file.split(".")[0]
>     new_vcf_name = f"{vcf_basename}_b38_withchr.vcf.gz"
> ```

The CHROM column of the clinvar vcf don't have the `chr` prefix. In the current update guide, we have to prepend the CHROM column with a `chr` prefix then modify the name of the clinavr vcf file by appending `hg38_withchr` to basename. 

But here, the vcf_name has _withchr but you didn't or haven't modify the content of the vcf to have a chr.

Could you please clarify?



_Code quote:_
```Python
    vcf_basename = recent_vcf_file.split(".")[0]
    new_vcf_name = f"{vcf_basename}_b38_withchr.vcf.gz"
```
___
*[`bin/clinvar_file_fetcher.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32ic1GCbx4lSg3TSyI:-O32ic1GCbx4lSg3TSyJ:b2rgarn) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/clinvar_file_fetcher.py#L164)):*
> ```Python
>     # the index file does not have a checksum on the ncbi website
>     tbi_basename = recent_tbi_file.split(".")[0]
>     new_tbi_name = f"{tbi_basename}_b38_withchr.vcf.gz.tbi"
> ```

above comment applies here if you want to modify name.



_Code quote:_
```Python
new_tbi_name = f"{tbi_basename}_b38_withchr.vcf.gz.tbi"
```
___
*[`bin/utils/util.py` line 151 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32moiU1wdZwdJ82LgO:-O32moiU1wdZwdJ82LgP:b5botfr) ([raw file](https://github.com/eastgenomics/phoenix/blob/efee386d1bf39dcb3780e33fd182cf7b14b5b7ba/bin/utils/util.py#L151)):*
> ```Python
>         file_path (str): path to local file to upload
>         project_id (str): DNAnexus project id of project to upload to
>         proj_folder_path (str, optional): DNAnexus folder path to upload to
> ```

I find the diff btw `file_path` and `proj_folder_path` a bit confusing. Will local or dnanexus file_name better distinguish both? If proj_folder_path is not given, won't the default path be root of project? Or can you specify a path from `file_path`? 



_Code quote:_
```Python
        file_path (str): path to local file to upload
        project_id (str): DNAnexus project id of project to upload to
        proj_folder_path (str, optional): DNAnexus folder path to upload to
```
___
*[`bin/utils/util.py` line 159 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32lcWmDA8HqEs-rfkZ:-O32lcWmDA8HqEs-rfk_:b-uv3fr8) ([raw file](https://github.com/eastgenomics/phoenix/blob/efee386d1bf39dcb3780e33fd182cf7b14b5b7ba/bin/utils/util.py#L159)):*
> ```Python
>         if not check_proj_folder_exists(project_id, proj_folder_path):
>             # create folder
>             project = dxpy.bindings.dxproject.DXProject(dxid=project_id)
> ```

You already imported `DXProject` from `dxpy.bindings.dxproject` why not use it directly?  It doesn't change functionality but to be consistent with your style eg you use the Class directly in `check_project_exists()` if you prefer this style then why not be consistent with it? 



_Code quote:_
```Python
 project = dxpy.bindings.dxproject.DXProject(dxid=project_id)
```

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/3)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @pofuoku and @Yu-jinKim)

___
*[`bin/clinvar_file_fetcher.py` line 126 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32aZtB-zJjqwlGTkv2:-O32x4RLDz0bZpzLvV80:bvm6ldi) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/clinvar_file_fetcher.py#L126)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Here, the comment and the code says you're checking for index file but the following RuntimeError says checksum couldn't be found. Do you want to check if `clinvar_checksum_file` in `file_list` or the comment on the error message an oversight?
</blockquote></details>

Thanks for spotting that. That was a copy paste typo and has been replaced with clinvar_checksum_file
___
*[`bin/clinvar_file_fetcher.py` line 156 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32gZZSBNOAY0iAPCqw:-O33-4Y-3Pox6fGHnEzO:b-g8ml2l) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/clinvar_file_fetcher.py#L156)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

The CHROM column of the clinvar vcf don't have the `chr` prefix. In the current update guide, we have to prepend the CHROM column with a `chr` prefix then modify the name of the clinavr vcf file by appending `hg38_withchr` to basename. 

But here, the vcf_name has _withchr but you didn't or haven't modify the content of the vcf to have a chr.

Could you please clarify?
</blockquote></details>

Ah, I should have added _GRCh38 instead. I've updated it now
___
*[`bin/clinvar_file_fetcher.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32ic1GCbx4lSg3TSyI:-O330NHb6h6HXuVMFhQN:b-xirv0t) ([raw file](https://github.com/eastgenomics/phoenix/blob/699d7be005f435625f8ed0688436da0e138d0d1a/bin/clinvar_file_fetcher.py#L164)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

above comment applies here if you want to modify name.
</blockquote></details>

I've updated this one as well
___
*[`bin/utils/util.py` line 151 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32moiU1wdZwdJ82LgO:-O32yWhh7ZwxlBQEq9X0:b-xlec8r) ([raw file](https://github.com/eastgenomics/phoenix/blob/efee386d1bf39dcb3780e33fd182cf7b14b5b7ba/bin/utils/util.py#L151)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

I find the diff btw `file_path` and `proj_folder_path` a bit confusing. Will local or dnanexus file_name better distinguish both? If proj_folder_path is not given, won't the default path be root of project? Or can you specify a path from `file_path`?
</blockquote></details>

The file_path argument is simply where the file is stored on the DNAnexus worker node during runtime. The proj_folder_path is the directory of the DNAnexus project specified by project_id you would like to upload the file to. Yes, if a folder is not given this will upload to the project root directory. The file name itself is the same on the DNAnexus project as the file stored on the DNAnexus worker node
___
*[`bin/utils/util.py` line 159 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/3#-O32lcWmDA8HqEs-rfkZ:-O32zM8V7WS6BqiDVdVN:b-pcbquy) ([raw file](https://github.com/eastgenomics/phoenix/blob/efee386d1bf39dcb3780e33fd182cf7b14b5b7ba/bin/utils/util.py#L159)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

You already imported `DXProject` from `dxpy.bindings.dxproject` why not use it directly?  It doesn't change functionality but to be consistent with your style eg you use the Class directly in `check_project_exists()` if you prefer this style then why not be consistent with it?
</blockquote></details>

The direct DXProject call was added later. This was to make the code look less cluttered. I've updated the old call to reference DXProject directly to make things consistent

**Review by pofuoku — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PolarisAstrum-NHS)

**Pull request merged**
