### PR TITLE
Get list of all b38 clinvar files

### PR DESCRIPTION
**Pull request by PolarisAstrum-NHS**
First version of Phoenix, designed to get a list of all clinvar b38 files available for download from ncbi website.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)

### CODE REVIEW

**Review by pofuoku — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)* status: all files reviewed, 3 unresolved discussions (waiting on @PolarisAstrum-NHS)

___
*[`bin/clinvar_annotation_update.py` line 11 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OWxM1ErYSIJLXfTzN:-O0OWxM1ErYSIJLXfTzO:b-x448lo) ([raw file](https://github.com/eastgenomics/phoenix/blob/df9db44dea819a191230bcd8392f8bf7eafaf6b5/bin/clinvar_annotation_update.py#L11)):*
> ```Python
> 
> def run_annotation_update(config_path) -> None:
>     # load config file
> ```

Did you intentionally leave out a docstring? I noticed you described this argument elsewhere, but it would be helpful to repeat it here and also include a summary of the function.

I assume this function is not complete and more details will be added in next PR because it is right now only printing out files in current directory on the clinVar server. Is that right?

Alternatively, would you like to isolate this function to simply return the file_list, which another function will take as input. That way you do not have to modify this function in the next PR. That also means it won't be called `run_annotation_update`.  What do you think? Or what do you have in mind?



_Code quote:_
```Python
 # load config file
```
___
*[`bin/clinvar_annotation_update.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0Oa3gl9os7csAkCcjO:-O0Oa3gm3aYVPZYoNiCL:b-zgd0ph) ([raw file](https://github.com/eastgenomics/phoenix/blob/df9db44dea819a191230bcd8392f8bf7eafaf6b5/bin/clinvar_annotation_update.py#L46)):*
> ```Python
>             "Error: path to config file must be specified when running"
>             + "clinvar_annotation_update.py"
>         )
> ```

You wouldn't want `run_annotation_update.py` to run if this condition is  not met. Right now it just prints out an error message but proceeds to running the script anyway. 

You can put the `run_annotation_update(sys.argv[1])` in and `if` block to ensure it only runs if num_args is 2. You can also use an assert statement or raise a ValueError similar to what you did in `clinvar_file_fetcher.py`



_Code quote:_
```Python
    if num_args < 2:
        print(
            "Error: path to config file must be specified when running"
            + "clinvar_annotation_update.py"
        )
```
___
*[`bin/clinvar_file_fetcher.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OfEDC5PC_TPRlEt6Y:-O0OfEDC5PC_TPRlEt6Z:b-14ih3u) ([raw file](https://github.com/eastgenomics/phoenix/blob/df9db44dea819a191230bcd8392f8bf7eafaf6b5/bin/clinvar_file_fetcher.py#L38)):*
> ```Python
> 
>     # safety feature to prevent too many requests to server
>     time.sleep(0.1)
> ```

I want to assume you are sure 0.1 seconds is enough sleep. ??



_Code quote:_
```Python
time.sleep(0.1)
```

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @pofuoku)

___
*[`bin/clinvar_annotation_update.py` line 11 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OWxM1ErYSIJLXfTzN:-O0OhnEC9CAbEQWde06M:b-jwdgyx) ([raw file](https://github.com/eastgenomics/phoenix/blob/df9db44dea819a191230bcd8392f8bf7eafaf6b5/bin/clinvar_annotation_update.py#L11)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Did you intentionally leave out a docstring? I noticed you described this argument elsewhere, but it would be helpful to repeat it here and also include a summary of the function.

I assume this function is not complete and more details will be added in next PR because it is right now only printing out files in current directory on the clinVar server. Is that right?

Alternatively, would you like to isolate this function to simply return the file_list, which another function will take as input. That way you do not have to modify this function in the next PR. That also means it won't be called `run_annotation_update`.  What do you think? Or what do you have in mind?
</blockquote></details>

This function is more of a placeholder to test functionality before I add more content in later updates. It will later become the central function for linking all of the update steps together. I've added a temporary docstring
___
*[`bin/clinvar_annotation_update.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0Oa3gl9os7csAkCcjO:-O0OiVzY4S3fUsDmbPeP:bnkctgg) ([raw file](https://github.com/eastgenomics/phoenix/blob/df9db44dea819a191230bcd8392f8bf7eafaf6b5/bin/clinvar_annotation_update.py#L46)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

You wouldn't want `run_annotation_update.py` to run if this condition is  not met. Right now it just prints out an error message but proceeds to running the script anyway. 

You can put the `run_annotation_update(sys.argv[1])` in and `if` block to ensure it only runs if num_args is 2. You can also use an assert statement or raise a ValueError similar to what you did in `clinvar_file_fetcher.py`
</blockquote></details>

Print statement replaced with raising a RuntimeError. Now it should fail before reaching run_annotation_update
___
*[`bin/clinvar_file_fetcher.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OfEDC5PC_TPRlEt6Y:-O0OisKz4dMhqF59cgEb:b-l0evwk) ([raw file](https://github.com/eastgenomics/phoenix/blob/df9db44dea819a191230bcd8392f8bf7eafaf6b5/bin/clinvar_file_fetcher.py#L38)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

I want to assume you are sure 0.1 seconds is enough sleep. ??
</blockquote></details>

Yes, that should be fine. It means that the maximum rate would be 10 requests per second should something go terribly wrong like calling it in an infinite loop. I had a 1 second delay before and it seemed to be an unnecessary overhead when multiple time.sleep() calls were used consecutively

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
Is there a readme for this repo? I have no idea what this is for, how to set it up, what it creates...

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1#-:-O0OtDbN0mNCaDoeJwla:b-96t87z)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @pofuoku and @PolarisAstrum-NHS)

___
*[`bin/clinvar_annotation_update.py` line 21 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0Ot7458b0S_heqSxBL:-O0Ot7458b0S_heqSxBM:b-ocjl5e) ([raw file](https://github.com/eastgenomics/phoenix/blob/4c9109e75145befbbf8cda14bd166eda9fbda08b/bin/clinvar_annotation_update.py#L21)):*
> ```Python
> 
>     file_list = []
>     ftp.retrlines('LIST', file_list.append)
> ```

could you leave a comment for this line?
___
*[`bin/clinvar_annotation_update.py` line 39 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OtvxlD7hZA1gZeC-t:-O0OtvxlD7hZA1gZeC-u:b-35afi9) ([raw file](https://github.com/eastgenomics/phoenix/blob/4c9109e75145befbbf8cda14bd166eda9fbda08b/bin/clinvar_annotation_update.py#L39)):*
> ```Python
>     with open(config_path, "r", encoding="utf8") as json_file:
>         config = json.load(json_file)
>     clinvar_base_link = config.get("CLINVAR_BASE_LINK")
> ```

could you add assertions here if the config file does not contain the expected keys?
___
*[`bin/clinvar_annotation_update.py` line 46 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OtSt55CPxFKhZueO9:-O0OtSt55CPxFKhZueOA:bfdg3ci) ([raw file](https://github.com/eastgenomics/phoenix/blob/4c9109e75145befbbf8cda14bd166eda9fbda08b/bin/clinvar_annotation_update.py#L46)):*
> ```Python
> if __name__ == "__main__":
>     # validate arguments
>     num_args = len(sys.argv)
> ```

please use argparse for verbosity and for proper documentation of the script and its usage
___
*[`bin/clinvar_file_fetcher.py` line 27 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OuLbz25wJof9TSl6t:-O0OuLbz25wJof9TSl6u:buab28z) ([raw file](https://github.com/eastgenomics/phoenix/blob/4c9109e75145befbbf8cda14bd166eda9fbda08b/bin/clinvar_file_fetcher.py#L27)):*
> ```Python
>     """
> 
>     # remove "https://" from link"
> ```

if this is the end goal, why not just use `.replace()`? especially if you use a config file that presumably is going to stay static

**Review by PolarisAstrum-NHS — COMMENTED** [review]
Added readme. This is the current planning document on confluence: https://cuhbioinformatics.atlassian.net/wiki/spaces/INF/pages/3262382111/Phoenix+Refactor+Plan+2

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1#-:-O0P-hgR3UPE_3LU7cPC:bdv97vf)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @pofuoku, @PolarisAstrum-NHS, and @Yu-jinKim)

___
*[`bin/clinvar_annotation_update.py` line 21 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0Ot7458b0S_heqSxBL:-O0PB0Tx8anCbHR61VNT:b-8b11j9) ([raw file](https://github.com/eastgenomics/phoenix/blob/4c9109e75145befbbf8cda14bd166eda9fbda08b/bin/clinvar_annotation_update.py#L21)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

could you leave a comment for this line?
</blockquote></details>

Added
___
*[`bin/clinvar_annotation_update.py` line 39 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OtvxlD7hZA1gZeC-t:-O0P7yBwENATzetnNn-j:br0rio5) ([raw file](https://github.com/eastgenomics/phoenix/blob/4c9109e75145befbbf8cda14bd166eda9fbda08b/bin/clinvar_annotation_update.py#L39)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

could you add assertions here if the config file does not contain the expected keys?
</blockquote></details>

Added assertion check
___
*[`bin/clinvar_annotation_update.py` line 46 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OtSt55CPxFKhZueO9:-O0PAe0iErkAZBOAqTPp:b-8b11j9) ([raw file](https://github.com/eastgenomics/phoenix/blob/4c9109e75145befbbf8cda14bd166eda9fbda08b/bin/clinvar_annotation_update.py#L46)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

please use argparse for verbosity and for proper documentation of the script and its usage
</blockquote></details>

Added
___
*[`bin/clinvar_file_fetcher.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OfEDC5PC_TPRlEt6Y:-O0P2X247gZxhBLsGkQ9:bs45dph) ([raw file](https://github.com/eastgenomics/phoenix/blob/df9db44dea819a191230bcd8392f8bf7eafaf6b5/bin/clinvar_file_fetcher.py#L38)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Yes, that should be fine. It means that the maximum rate would be 10 requests per second should something go terribly wrong like calling it in an infinite loop. I had a 1 second delay before and it seemed to be an unnecessary overhead when multiple time.sleep() calls were used consecutively
</blockquote></details>

I've changed it to 0.5 seconds just to be safe
___
*[`bin/clinvar_file_fetcher.py` line 27 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OuLbz25wJof9TSl6t:-O0P30Jg3sD-BQhQX9RG:bfyi4vj) ([raw file](https://github.com/eastgenomics/phoenix/blob/4c9109e75145befbbf8cda14bd166eda9fbda08b/bin/clinvar_file_fetcher.py#L27)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

if this is the end goal, why not just use `.replace()`? especially if you use a config file that presumably is going to stay static
</blockquote></details>

It's there in case the link changes in future. For example, if the domain for clinvar files changed, someone would manually edit the config file. Then if they add a malformed link, it would be picked up here.
Phoenix is also planned to do more than just clinvar updates. Cosmic and HGMD annotation resource updates are planned for future versions

**Review by pofuoku — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)* status: all files reviewed, 5 unresolved discussions (waiting on @PolarisAstrum-NHS and @Yu-jinKim)

___
*[`bin/clinvar_annotation_update.py` line 50 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0PGgQU1SxDqDm6PR6G:-O0PGgQU1SxDqDm6PR6H:bcvn12n) ([raw file](https://github.com/eastgenomics/phoenix/blob/6f1f69611cf45ce5b23bf765847f0682cbe1f484/bin/clinvar_annotation_update.py#L50)):*
> ```Python
>         raise RuntimeError(
>             "Config file does not contain expected keys"
>         )
> ```

If you're using assert here, it would be cleaner to remove the try-except block and do something like this instead:
`assert keys in config, "Config file does not contain expected keys"`

Unless you have other reasons for implicitly raising a RuntimeError which I can't think of??? I'd like to know what Yun-jinKim thinks, 'cos I might be wrong.



_Code quote:_
```Python
    try:
        assert keys in config
    except AssertionError:
        raise RuntimeError(
            "Config file does not contain expected keys"
        )
```
___
*[`bin/clinvar_file_fetcher.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0OfEDC5PC_TPRlEt6Y:-O0PJdQ6Aw6KtQVo84Ap:b-uv4ta) ([raw file](https://github.com/eastgenomics/phoenix/blob/df9db44dea819a191230bcd8392f8bf7eafaf6b5/bin/clinvar_file_fetcher.py#L38)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

I've changed it to 0.5 seconds just to be safe
</blockquote></details>

Thanks for the clarification.

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @pofuoku and @Yu-jinKim)

___
*[`bin/clinvar_annotation_update.py` line 50 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0PGgQU1SxDqDm6PR6G:-O0SgTGb4q5d4bQCKBLR:bpws16o) ([raw file](https://github.com/eastgenomics/phoenix/blob/6f1f69611cf45ce5b23bf765847f0682cbe1f484/bin/clinvar_annotation_update.py#L50)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

If you're using assert here, it would be cleaner to remove the try-except block and do something like this instead:
`assert keys in config, "Config file does not contain expected keys"`

Unless you have other reasons for implicitly raising a RuntimeError which I can't think of??? I'd like to know what Yun-jinKim thinks, 'cos I might be wrong.
</blockquote></details>

I raise Runtime errors to explicitly state that this is expected behaviour. This means that later I can write a try catch block which captures Runtime errors and not any other kind of error. For example, if I caught any exception using Exception (instead of Runtime), it is possible that I could accidentally catch unintended behaviour.

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @pofuoku and @Yu-jinKim)

___
*[`bin/clinvar_annotation_update.py` line 50 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/1#-O0PGgQU1SxDqDm6PR6G:-O0SkSY3B9WfIjNDa9vo:b-gghp3b) ([raw file](https://github.com/eastgenomics/phoenix/blob/6f1f69611cf45ce5b23bf765847f0682cbe1f484/bin/clinvar_annotation_update.py#L50)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

I raise Runtime errors to explicitly state that this is expected behaviour. This means that later I can write a try catch block which captures Runtime errors and not any other kind of error. For example, if I caught any exception using Exception (instead of Runtime), it is possible that I could accidentally catch unintended behaviour.
</blockquote></details>

There isn't much point in having the assertion error if I catch it immediately and throw a different exception. I replaced it with an if statement, which cleans up the code a bit

**Review by pofuoku — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)* status: all files reviewed, 1 unresolved discussion (waiting on @pofuoku)

**Review by pofuoku — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PolarisAstrum-NHS)

**Pull request merged**
