### PR TITLE
Development clinvar annotation update step 1 e

### PR DESCRIPTION
**Pull request by PolarisAstrum-NHS**
Added:

- Finding the latest clinvar annotation resource file with its index
- Check if date of most recent clinvar file is within date range of 8 weeks from present
- MIT license
- Improved readme files

Link to successful DNAnexus job: https://platform.dnanexus.com/panx/projects/GkxxZq843Zq2f0Gk3Z40p7BJ/monitor/job/Gp1ykKQ43Zq0GZXkQfGP7kgg

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)

### CODE REVIEW

**Review by pofuoku — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)* status: all files reviewed, 6 unresolved discussions (waiting on @PolarisAstrum-NHS)

___
*[`README.md` line 25 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0ncfB10aXThv_xGWFz:-O0ncfB23Vl5xW2z3C2f:b-2iziw6) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/README.md#L25)):*
> ```Markdown
> 
> To set off the nextflow DNAnexus applet, run the following command, replacing the applet ID you have generated and the DNAnexus file path with the location of the config file you wish to use on DNAnexus.
> dx run applet-GkyY1Vj43Zq9Y5B6v1Q89XFg -i nextflow_pipeline_params="--config_path="dx://project-GkxxZq843Zq2f0Gk3Z40p7BJ:/Config/phoenix_config.json""
> ```

This should have been caught in last PR. Since this applet id will keep changing, we can run the applet using the name; that way you do not have to modify the ID everytime it changes.  In addition, the path to config can be a place holder. Then remind the user to replace with the actual path of the config file. eg:

`dx run phoenix -i nextflow_pipeline_params="--config_path=dx://project-xxx:/path/to/config"`

or simply an emply {} as a placeholder. 

Just a suggestion. what do you think?



_Code quote:_
```Markdown
dx run applet-GkyY1Vj43Zq9Y5B6v1Q89XFg -i nextflow_pipeline_params="--config_path="dx://project-GkxxZq843Zq2f0Gk3Z40p7BJ:/Config/phoenix_config.json""
```
___
*[`README.md` line 45 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0ng31p6ErH3zZHF-OS:-O0ng31p6ErH3zZHF-OT:b9m4pc) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/README.md#L45)):*
> ```Markdown
> ## What does this app output?
> 
> This app does not have an output
> ```

I understand what you mean here; but technically the phoenix itself has output for example, the clinavr files and other files it will eventually upload to a DNAnexus project. I'm not sure if it should be here but can you state this somewhere so it can be clear.

Then as a DNAnexus app, the output filed shows a `nextflow_log`. This might be useful for debugging. You might also want to specify a  folder to send the log file to in the above dx run command using the destination flag eg;

```
dx run phoenix \
-inextflow_pipeline_params={} \
--destination={}
```



_Code quote:_
```Markdown
This app does not have an output
```
___
*[`bin/clinvar_annotation_update.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nleB2CWCPn1VD9EiS:-O0nleB2CWCPn1VD9EiT:becaah7) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_annotation_update.py#L38)):*
> ```Python
>             "Most recent clinvar file availble for download is from over"
>             + f" {num_weeks_ago} weeks ago"
>         )
> ```

I'm not sure of hard coding the num_weeks_ago inside the main function of the script. It would be better if it an input to a function ( a default input).

Better still I would put this whole block in a function, which make the script more modular and also easy for unit testing. For example the function could be called check or verify_clinvar_file_date or something like that. Then it takes the `num_weeks_ago` and `clinvar_version_date` as arguments. 

I pointed this out last time also. The `run_annotation_update()` is the main entry point to the script; you can name it `main()` to be more pythonic. Its not neccessay but it's just a common convention of naming your main entry point. Then the main funtion simply calls other functions just like in this case, it's calling `load_config()`, `connect_to_website()`, `get_most_recent_clinvar_file_info()` and so on. That way we isolate all the functions and can test them seperately. Like I said, this is just a convention but it makes each component isolated, easily edited and tested.  



_Code quote:_
```Python
    num_weeks_ago = 8
    earlier_date = (
        datetime.date.today() - datetime.timedelta(weeks=num_weeks_ago)
    )
    if clinvar_version_date < earlier_date:
        raise RuntimeError(
            "Most recent clinvar file availble for download is from over"
            + f" {num_weeks_ago} weeks ago"
        )
```
___
*[`bin/clinvar_annotation_update.py` line 63 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nq7B9B-q0YiWnQr96:-O0nq7B9B-q0YiWnQr97:bhf5dbh) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_annotation_update.py#L63)):*
> ```Python
>     ]
>     if not all(e in config for e in keys):
>         raise RuntimeError("Config file does not contain expected keys")
> ```

We all missed this last time. Could you add Raises Runtime error to the docstring.
In addition, although the names `clinvar_base_link` and `clinvar_link_path` are self descriptive, you could further clarify what they are just like you did for the `config_path` arg



_Code quote:_
```Python
    if not all(e in config for e in keys):
        raise RuntimeError("Config file does not contain expected keys")
```
___
*[`bin/clinvar_file_fetcher.py` line 82 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nyTDc0ldozvMuFf4A:-O0nyTDc0ldozvMuFf4B:bx6qr2t) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_file_fetcher.py#L82)):*
> ```Python
>         if not file_info.strip():
>             continue
>         # get name portion of file information
> ```

Why not add more logging to the script. A for example you can simply print the `file_info` . It might be usefull to see everything going on in the log file incase we might need to reference it or do some debugging. 

Additionally, you can use the print statement to explain what each block of code is doing. eg. 
print("getting list of file-infos")
 
It will be useful to add more print statement to other sections of this script as well; so we have tings to look at in the log files.



_Code quote:_
```Python
    for file_info in file_info_list:
        # if file info is empty, ignore
        if not file_info.strip():
            continue
        # get name portion of file information
```
___
*[`bin/clinvar_file_fetcher.py` line 113 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nxYyp2WoQzaNNGKHx:-O0nxYyp2WoQzaNNGKHy:byv93sc) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_file_fetcher.py#L113)):*
> ```Python
>             "Matching index could not be found for most recent ClinVar VCF"
>             + " on ncbi website"
>         )
> ```

You can repeat this block for the expected checksum.
`.vcf.gz.md5`

Then include it in the output. Unless you have other way of doing this.



_Code quote:_
```Python
    # get corresponding .vcf.gz.tbi file based on vcf name
    recent_tbi_file = recent_vcf_file + ".tbi"
    # check index file exists on website
    if recent_tbi_file not in file_list:
        raise RuntimeError(
            "Matching index could not be found for most recent ClinVar VCF"
            + " on ncbi website"
        )
```

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @pofuoku and @PolarisAstrum-NHS)

___
*[`README.md` line 25 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0ncfB10aXThv_xGWFz:-O0s6a_QA_ekzV9HQ8YN:bxp7ac2) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/README.md#L25)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

This should have been caught in last PR. Since this applet id will keep changing, we can run the applet using the name; that way you do not have to modify the ID everytime it changes.  In addition, the path to config can be a place holder. Then remind the user to replace with the actual path of the config file. eg:

`dx run phoenix -i nextflow_pipeline_params="--config_path=dx://project-xxx:/path/to/config"`

or simply an emply {} as a placeholder. 

Just a suggestion. what do you think?
</blockquote></details>

Yes, that seems like a good idea. I've added it to the readme
___
*[`README.md` line 45 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0ng31p6ErH3zZHF-OS:-O0s6mRE5zSnYEViNWjX:b607c11) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/README.md#L45)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

I understand what you mean here; but technically the phoenix itself has output for example, the clinavr files and other files it will eventually upload to a DNAnexus project. I'm not sure if it should be here but can you state this somewhere so it can be clear.

Then as a DNAnexus app, the output filed shows a `nextflow_log`. This might be useful for debugging. You might also want to specify a  folder to send the log file to in the above dx run command using the destination flag eg;

```
dx run phoenix \
-inextflow_pipeline_params={} \
--destination={}
```
</blockquote></details>

Yes, I can add the outputs here when implemented. However, as there are no outputs in the current version I think it's best to leave it for a later PR.
I've added the `--destination argument` to the readme.
___
*[`bin/clinvar_annotation_update.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nleB2CWCPn1VD9EiS:-O0sLFgu9G_mQ4WyxRf6:b6kobv) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_annotation_update.py#L38)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

I'm not sure of hard coding the num_weeks_ago inside the main function of the script. It would be better if it an input to a function ( a default input).

Better still I would put this whole block in a function, which make the script more modular and also easy for unit testing. For example the function could be called check or verify_clinvar_file_date or something like that. Then it takes the `num_weeks_ago` and `clinvar_version_date` as arguments. 

I pointed this out last time also. The `run_annotation_update()` is the main entry point to the script; you can name it `main()` to be more pythonic. Its not neccessay but it's just a common convention of naming your main entry point. Then the main funtion simply calls other functions just like in this case, it's calling `load_config()`, `connect_to_website()`, `get_most_recent_clinvar_file_info()` and so on. That way we isolate all the functions and can test them seperately. Like I said, this is just a convention but it makes each component isolated, easily edited and tested.
</blockquote></details>

I moved the hardcoded value to the config file and added a try catch for value types there. This catches the error of failing to cast a string to an int when read from the config json.

As the date range check will likely be used elsewhere later in development, I moved it to a function in the utils module and removed any references to the clinvar update.

The reason I was hesitant to name it `main()` before was because I had several "main" functions in the initial design. One for the clinvar annotation update, one for the vep config update, and one for the helios reports workflow update. However, the module each is contained in (e.g., `clinvar_annotation_update.py`) should be enough to differentiate them. I've renamed it to main.
___
*[`bin/clinvar_annotation_update.py` line 63 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nq7B9B-q0YiWnQr96:-O0sL7z88yR1jcgL_P3t:b-62d4qv) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_annotation_update.py#L63)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

We all missed this last time. Could you add Raises Runtime error to the docstring.
In addition, although the names `clinvar_base_link` and `clinvar_link_path` are self descriptive, you could further clarify what they are just like you did for the `config_path` arg
</blockquote></details>

I appended the docstring with the needed information
___
*[`bin/clinvar_file_fetcher.py` line 82 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nyTDc0ldozvMuFf4A:-O0rVuPz-V_Aa0--fWMt:b-kxi3cf) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_file_fetcher.py#L82)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Why not add more logging to the script. A for example you can simply print the `file_info` . It might be usefull to see everything going on in the log file incase we might need to reference it or do some debugging. 

Additionally, you can use the print statement to explain what each block of code is doing. eg. 
print("getting list of file-infos")
 
It will be useful to add more print statement to other sections of this script as well; so we have tings to look at in the log files.
</blockquote></details>

I think it's best to avoid too many print statements. For denoting larger sections sure, but as you get more granular it gets less useful from the perspective of someone reading through the log file. This kind of logging for debugging purposes will be handled by the progress tracker module in a later update
___
*[`bin/clinvar_file_fetcher.py` line 113 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nxYyp2WoQzaNNGKHx:-O0rY_MPAq5myEky0aZU:bcw0ukt) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_file_fetcher.py#L113)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

You can repeat this block for the expected checksum.
`.vcf.gz.md5`

Then include it in the output. Unless you have other way of doing this.
</blockquote></details>

I need to know how I'll be implementing file downloads and checksums before I do this. For example, if the file integrity check I'm using automatically searches the ftp directory for the checksum, this would be an unnecessary step. I can add this during the next PR as part of the file download step if required

**Review by pofuoku — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> Dismissed @pofuoku from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)* status: all files reviewed, 2 unresolved discussions (waiting on @PolarisAstrum-NHS)

___
*[`bin/clinvar_annotation_update.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nleB2CWCPn1VD9EiS:-O0x4c4xAZ4pS3UAIxWX:bd4xl6z) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_annotation_update.py#L38)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

I moved the hardcoded value to the config file and added a try catch for value types there. This catches the error of failing to cast a string to an int when read from the config json.

As the date range check will likely be used elsewhere later in development, I moved it to a function in the utils module and removed any references to the clinvar update.

The reason I was hesitant to name it `main()` before was because I had several "main" functions in the initial design. One for the clinvar annotation update, one for the vep config update, and one for the helios reports workflow update. However, the module each is contained in (e.g., `clinvar_annotation_update.py`) should be enough to differentiate them. I've renamed it to main.
</blockquote></details>

Brilliant to move it config file. It will easy to modify should one want a different behaviour. In addition, could you add that to the structure of the config in README; you can choose to do this in later PR but can also easily forget as the config file grows. Also the order of the functions doesn't really matter so I assume it's your preferred style to put the main function first.
___
*[`bin/clinvar_annotation_update.py` line 66 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0xAji42BDiS3ZOdT37:-O0xAji42BDiS3ZOdT38:bm0omhf) ([raw file](https://github.com/eastgenomics/phoenix/blob/b8b6c74ece2a1b2b79154ae6d78f854917ac341d/bin/clinvar_annotation_update.py#L66)):*
> ```Python
>         "CLINVAR_BASE_LINK",
>         "CLINVAR_LINK_PATH_B38"
>     ]
> ```

Since you added a new entry to config; did you deliberately omit it here?

I think the try-except block will pick it when trying to cast a None value to int anyway; but just want to clarify if you will also want to put it here as well.



_Code quote:_
```Python
    keys = [
        "CLINVAR_BASE_LINK",
        "CLINVAR_LINK_PATH_B38"
    ]
```
___
*[`bin/utils/util.py` line 14 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0x0Glx79QUYL6nf-a2:-O0x0Glx79QUYL6nf-a3:b-ojwc1x) ([raw file](https://github.com/eastgenomics/phoenix/blob/b8b6c74ece2a1b2b79154ae6d78f854917ac341d/bin/utils/util.py#L14)):*
> ```Python
>         comparison_date (datetime.date): Date to compare
>         num_weeks_ago (int, optional): Check date is within the past
>             number of weeks ago. Defaults to 8.
> ```

Can you please remind me again why you choose 8 weeks. This was stated in the design doc and  you must have explained this before; but sorry for taking you back.

Considering that phoenix would must likely be run weekly; imagine a scenerio where the current clinvar file in prod is a week old then when phoenix checks clinvar database and the most recent version there is also a week old (maybe for some reasons, clinavr was some few hours or a day late). In this scenario, phoenix will check if the version is with 8 weeks old and download it because it is only 1 week old. But will this be the behaviour you want? You will simply be downloading same version in prod. 

Like I said, I might have missed this explaination, so please clarify again.



_Code quote:_
```Python
 Defaults to 8.
```

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @pofuoku)

___
*[`bin/clinvar_annotation_update.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0nleB2CWCPn1VD9EiS:-O0xDM8S0GjnAUFawvZn:bqvwr3l) ([raw file](https://github.com/eastgenomics/phoenix/blob/0ed67dc27946c5208a317ecff59d0a59e63a5640/bin/clinvar_annotation_update.py#L38)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Brilliant to move it config file. It will easy to modify should one want a different behaviour. In addition, could you add that to the structure of the config in README; you can choose to do this in later PR but can also easily forget as the config file grows. Also the order of the functions doesn't really matter so I assume it's your preferred style to put the main function first.
</blockquote></details>

Added now
___
*[`bin/clinvar_annotation_update.py` line 66 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0xAji42BDiS3ZOdT37:-O0xC7bTB3ywJSHPO0tR:bcct711) ([raw file](https://github.com/eastgenomics/phoenix/blob/b8b6c74ece2a1b2b79154ae6d78f854917ac341d/bin/clinvar_annotation_update.py#L66)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Since you added a new entry to config; did you deliberately omit it here?

I think the try-except block will pick it when trying to cast a None value to int anyway; but just want to clarify if you will also want to put it here as well.
</blockquote></details>

Ah, I thought I had already added it to the list. Added now
___
*[`bin/utils/util.py` line 14 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0x0Glx79QUYL6nf-a2:-O0xDY8NE5SWk_652Tvn:b6quhi1) ([raw file](https://github.com/eastgenomics/phoenix/blob/b8b6c74ece2a1b2b79154ae6d78f854917ac341d/bin/utils/util.py#L14)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Can you please remind me again why you choose 8 weeks. This was stated in the design doc and  you must have explained this before; but sorry for taking you back.

Considering that phoenix would must likely be run weekly; imagine a scenerio where the current clinvar file in prod is a week old then when phoenix checks clinvar database and the most recent version there is also a week old (maybe for some reasons, clinavr was some few hours or a day late). In this scenario, phoenix will check if the version is with 8 weeks old and download it because it is only 1 week old. But will this be the behaviour you want? You will simply be downloading same version in prod. 

Like I said, I might have missed this explaination, so please clarify again.
</blockquote></details>

This was an additional sense check requested by wook. Anything outside of a reasonable range will be ignored. There will be additional checks for the dev version matching prod in the scenario you described. If the version in prod is the same or newer, the update will be exited

**Review by pofuoku — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PolarisAstrum-NHS)

___
*[`bin/utils/util.py` line 14 at r2](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0x0Glx79QUYL6nf-a2:-O0xFEJr-HSoP5T_pOpe:b-j80qcn) ([raw file](https://github.com/eastgenomics/phoenix/blob/b8b6c74ece2a1b2b79154ae6d78f854917ac341d/bin/utils/util.py#L14)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

This was an additional sense check requested by wook. Anything outside of a reasonable range will be ignored. There will be additional checks for the dev version matching prod in the scenario you described. If the version in prod is the same or newer, the update will be exited
</blockquote></details>

Thanks for clarifying this.

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)* status: all files reviewed, 1 unresolved discussion (waiting on @PolarisAstrum-NHS)

___
*[`bin/utils/util.py` line 9 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0xIpoI2UnQDRmNcRQo:-O0xIpoI2UnQDRmNcRQp:b85tzrb) ([raw file](https://github.com/eastgenomics/phoenix/blob/a8ddff8f2910b71ed842125c6f37085275e95dff/bin/utils/util.py#L9)):*
> ```Python
> 
> def is_date_within_n_weeks(comparison_date, num_weeks_ago=8) -> bool:
>     """_summary_
> ```

missing summary

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @pofuoku and @Yu-jinKim)

___
*[`bin/utils/util.py` line 9 at r3](https://reviewable.io/reviews/eastgenomics/phoenix/2#-O0xIpoI2UnQDRmNcRQo:-O0xJvQM5fDhj5wAUfi9:b-8b11j9) ([raw file](https://github.com/eastgenomics/phoenix/blob/a8ddff8f2910b71ed842125c6f37085275e95dff/bin/utils/util.py#L9)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

missing summary
</blockquote></details>

Added

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/phoenix/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PolarisAstrum-NHS)

**Pull request merged**
